# Site settings
title: Growth
header-img: "img/zhihu.jpg"
tagline: "cn"
description: "柯子 | Stay Hungry, Stay Foolish."
baseurl: ""
url: "http://kerzzi.github.io"

# About/contact
owner:
  name: "Kerzzi"
  email: kerzzi@outlook.com
  bio: "Simplicity is always overwhelming!"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username: kerzzi
twitter_username: kerzzi123
github_username: Kerzzi
facebook_username: 刘铮
weibo_username: Kerzzi
zhihu_username: kerzzi

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Kerzzi"
      header-img: "img/blue.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : kerzzi
  disqus :
      short_name : kerzzi

# Analytics and webmaster tools stuff goes here
google_analytics: 'UA-103039981-1'
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
